// Code generated by authz/gen from schema.cedarschema. DO NOT EDIT.

package authz

import (
	_ "embed"

	cedar "github.com/cedar-policy/cedar-go"
)

//go:embed schema.cedarschema
var Schema string

const (
	InventoryType             cedar.EntityType = "Mixology::Inventory"
	ActionType                cedar.EntityType = "Mixology::Inventory::Action"
	InventoryIngredientIDAttr                  = "IngredientID"
	InventoryUnitAttr                          = "Unit"
)

var (
	ActionAdjust = cedar.NewEntityUID(ActionType, "adjust")
	ActionGet    = cedar.NewEntityUID(ActionType, "get")
	ActionList   = cedar.NewEntityUID(ActionType, "list")
	ActionSet    = cedar.NewEntityUID(ActionType, "set")
	ActionTag    = cedar.NewEntityUID(ActionType, "tag")
	ActionUntag  = cedar.NewEntityUID(ActionType, "untag")
)

// Inventory is the Cedar-facing authorization model for Mixology::Inventory.
type Inventory struct {
	UID          cedar.EntityUID
	Tags         map[string]string
	IngredientID cedar.EntityUID
	Unit         string
}

// CedarEntity converts m to the entity shape declared in schema.cedarschema.
func (m Inventory) CedarEntity() cedar.Entity {
	tags := make(cedar.RecordMap, len(m.Tags))
	for key, value := range m.Tags {
		tags[cedar.String(key)] = cedar.String(value)
	}

	return cedar.Entity{
		UID:     cedar.NewEntityUID(InventoryType, m.UID.ID),
		Parents: cedar.NewEntityUIDSet(),
		Attributes: cedar.NewRecord(cedar.RecordMap{
			InventoryIngredientIDAttr: cedar.EntityUID(m.IngredientID),
			InventoryUnitAttr:         cedar.String(m.Unit),
		}),
		Tags: cedar.NewRecord(tags),
	}
}
