// Code generated by authz/gen from schema.cedarschema. DO NOT EDIT.

package authz

import (
	_ "embed"
	"sync"

	cedar "github.com/cedar-policy/cedar-go"
	"github.com/cedar-policy/cedar-go/x/exp/schema"
	"github.com/cedar-policy/cedar-go/x/exp/schema/resolved"
	"github.com/cedar-policy/cedar-go/x/exp/schema/validate"
)

//go:embed schema.cedarschema
var Schema string

const (
	InventoryType             cedar.EntityType = "Mixology::Inventory"
	ResourceType              cedar.EntityType = InventoryType
	ActionType                cedar.EntityType = "Mixology::Inventory::Action"
	InventoryIngredientIDAttr                  = "IngredientID"
	InventoryUnitAttr                          = "Unit"
)

var (
	schemaOnce     sync.Once
	resolvedSchema *resolved.Schema
	schemaErr      error
)

// ValidateEntity validates entity against the module's Cedar schema.
func ValidateEntity(entity cedar.Entity) error {
	schemaOnce.Do(func() {
		var parsed schema.Schema
		parsed.SetFilename("schema.cedarschema")
		if schemaErr = parsed.UnmarshalCedar([]byte(Schema)); schemaErr != nil {
			return
		}
		resolvedSchema, schemaErr = parsed.Resolve()
	})
	if schemaErr != nil {
		return schemaErr
	}
	return validate.New(resolvedSchema).Entity(entity)
}

var (
	ActionAdjust = cedar.NewEntityUID(ActionType, "adjust")
	ActionGet    = cedar.NewEntityUID(ActionType, "get")
	ActionList   = cedar.NewEntityUID(ActionType, "list")
	ActionSet    = cedar.NewEntityUID(ActionType, "set")
	ActionTag    = cedar.NewEntityUID(ActionType, "tag")
	ActionUntag  = cedar.NewEntityUID(ActionType, "untag")
)

// Inventory is the Cedar-facing authorization model for Mixology::Inventory.
type Inventory struct {
	UID          cedar.EntityUID
	Tags         map[string]string
	IngredientID cedar.EntityUID
	Unit         string
}

// CedarEntity converts m to the entity shape declared in schema.cedarschema.
func (m Inventory) CedarEntity() cedar.Entity {
	tags := make(cedar.RecordMap, len(m.Tags))
	for key, value := range m.Tags {
		tags[cedar.String(key)] = cedar.String(value)
	}

	return cedar.Entity{
		UID:     cedar.NewEntityUID(InventoryType, m.UID.ID),
		Parents: cedar.NewEntityUIDSet(),
		Attributes: cedar.NewRecord(cedar.RecordMap{
			InventoryIngredientIDAttr: cedar.NewEntityUID("Mixology::Ingredient", m.IngredientID.ID),
			InventoryUnitAttr:         cedar.String(m.Unit),
		}),
		Tags: cedar.NewRecord(tags),
	}
}
