// Code generated by authz/gen from schema.cedarschema. DO NOT EDIT.

package authz_test

import (
	"testing"

	moduleauthz "github.com/TheFellow/go-modular-monolith/app/domains/inventory/authz"
	"github.com/TheFellow/go-modular-monolith/pkg/testutil"
	cedar "github.com/cedar-policy/cedar-go"
)

func TestInventoryCedarEntity(t *testing.T) {
	t.Parallel()

	model := moduleauthz.Inventory{
		UID:          cedar.NewEntityUID("Wrong::Type", "test-id"),
		IngredientID: cedar.NewEntityUID("Test::Reference", "test-ingredientid"),
		Unit:         "test-unit",
	}

	got := model.CedarEntity()
	want := cedar.Entity{
		UID:     cedar.NewEntityUID(moduleauthz.InventoryType, "test-id"),
		Parents: cedar.NewEntityUIDSet(),
		Attributes: cedar.NewRecord(cedar.RecordMap{
			moduleauthz.InventoryIngredientIDAttr: cedar.NewEntityUID("Test::Reference", "test-ingredientid"),
			moduleauthz.InventoryUnitAttr:         cedar.String("test-unit"),
		}),
		Tags: cedar.NewRecord(nil),
	}

	testutil.Equals(t, got, want)
}
