// Code generated by authz/gen from schema.cedarschema. DO NOT EDIT.

package authz

import (
	"testing"

	cedar "github.com/cedar-policy/cedar-go"
)

func TestInventoryCedarEntity(t *testing.T) {
	t.Parallel()

	model := Inventory{
		UID:          cedar.NewEntityUID("Wrong::Type", "test-id"),
		IngredientID: cedar.NewEntityUID("Test::Reference", "test-ingredientid"),
		Unit:         "test-unit",
	}

	got := model.CedarEntity()
	want := cedar.Entity{
		UID:     cedar.NewEntityUID(InventoryType, "test-id"),
		Parents: cedar.NewEntityUIDSet(),
		Attributes: cedar.NewRecord(cedar.RecordMap{
			InventoryIngredientIDAttr: cedar.NewEntityUID("Test::Reference", "test-ingredientid"),
			InventoryUnitAttr:         cedar.String("test-unit"),
		}),
		Tags: cedar.NewRecord(nil),
	}

	if !want.Equal(got) {
		t.Errorf("CedarEntity() = %#v, want %#v", got, want)
	}
}
