// Code generated by authz/gen from schema.cedarschema. DO NOT EDIT.

package authz_test

import (
	"testing"

	moduleauthz "github.com/TheFellow/go-modular-monolith/app/domains/inventory/authz"
	"github.com/TheFellow/go-modular-monolith/pkg/testutil"
	cedar "github.com/cedar-policy/cedar-go"
	"github.com/cedar-policy/cedar-go/x/exp/schema"
	"github.com/cedar-policy/cedar-go/x/exp/schema/validate"
)

func TestInventoryCedarEntity(t *testing.T) {
	t.Parallel()

	model := moduleauthz.Inventory{
		UID:          cedar.NewEntityUID("Wrong::Type", "test-id"),
		Tags:         map[string]string{"audience": "members", "featured": ""},
		IngredientID: cedar.NewEntityUID("Mixology::Ingredient", "test-ingredientid"),
		Unit:         "test-unit",
	}

	got := model.CedarEntity()
	want := cedar.Entity{
		UID:     cedar.NewEntityUID(moduleauthz.InventoryType, "test-id"),
		Parents: cedar.NewEntityUIDSet(),
		Attributes: cedar.NewRecord(cedar.RecordMap{
			moduleauthz.InventoryIngredientIDAttr: cedar.NewEntityUID("Mixology::Ingredient", "test-ingredientid"),
			moduleauthz.InventoryUnitAttr:         cedar.String("test-unit"),
		}),
		Tags: cedar.NewRecord(cedar.RecordMap{
			"audience": cedar.String("members"),
			"featured": cedar.String(""),
		}),
	}

	testutil.Equals(t, got, want)
	var parsed schema.Schema
	testutil.Ok(t, parsed.UnmarshalCedar([]byte(moduleauthz.Schema)))
	resolved, err := parsed.Resolve()
	testutil.Ok(t, err)
	testutil.Ok(t, validate.New(resolved).Entity(got))
}
