// Code generated by authz/gen from schema.cedarschema. DO NOT EDIT.

package authz

import (
	"testing"

	cedar "github.com/cedar-policy/cedar-go"
)

func TestDrinkCedarEntity(t *testing.T) {
	t.Parallel()

	model := Drink{
		UID:         cedar.NewEntityUID("Wrong::Type", "test-id"),
		Category:    "test-category",
		Description: "test-description",
		Glass:       "test-glass",
		Name:        "test-name",
	}

	got := model.CedarEntity()
	want := cedar.Entity{
		UID:     cedar.NewEntityUID(DrinkType, "test-id"),
		Parents: cedar.NewEntityUIDSet(),
		Attributes: cedar.NewRecord(cedar.RecordMap{
			DrinkCategoryAttr:    cedar.String("test-category"),
			DrinkDescriptionAttr: cedar.String("test-description"),
			DrinkGlassAttr:       cedar.String("test-glass"),
			DrinkNameAttr:        cedar.String("test-name"),
		}),
		Tags: cedar.NewRecord(nil),
	}

	if !want.Equal(got) {
		t.Errorf("CedarEntity() = %#v, want %#v", got, want)
	}
}
