// Code generated by authz/gen from schema.cedarschema. DO NOT EDIT.

package authz

import (
	_ "embed"
	"sync"

	cedar "github.com/cedar-policy/cedar-go"
	"github.com/cedar-policy/cedar-go/x/exp/schema"
	"github.com/cedar-policy/cedar-go/x/exp/schema/resolved"
	"github.com/cedar-policy/cedar-go/x/exp/schema/validate"
)

//go:embed schema.cedarschema
var Schema string

const (
	DrinkType            cedar.EntityType = "Mixology::Drink"
	ResourceType         cedar.EntityType = DrinkType
	ActionType           cedar.EntityType = "Mixology::Drink::Action"
	DrinkCategoryAttr                     = "Category"
	DrinkDescriptionAttr                  = "Description"
	DrinkGlassAttr                        = "Glass"
	DrinkNameAttr                         = "Name"
)

var (
	schemaOnce     sync.Once
	resolvedSchema *resolved.Schema
	schemaErr      error
)

// ValidateEntity validates entity against the module's Cedar schema.
func ValidateEntity(entity cedar.Entity) error {
	schemaOnce.Do(func() {
		var parsed schema.Schema
		parsed.SetFilename("schema.cedarschema")
		if schemaErr = parsed.UnmarshalCedar([]byte(Schema)); schemaErr != nil {
			return
		}
		resolvedSchema, schemaErr = parsed.Resolve()
	})
	if schemaErr != nil {
		return schemaErr
	}
	return validate.New(resolvedSchema).Entity(entity)
}

var (
	ActionCreate = cedar.NewEntityUID(ActionType, "create")
	ActionDelete = cedar.NewEntityUID(ActionType, "delete")
	ActionGet    = cedar.NewEntityUID(ActionType, "get")
	ActionList   = cedar.NewEntityUID(ActionType, "list")
	ActionTag    = cedar.NewEntityUID(ActionType, "tag")
	ActionUntag  = cedar.NewEntityUID(ActionType, "untag")
	ActionUpdate = cedar.NewEntityUID(ActionType, "update")
)

// Drink is the Cedar-facing authorization model for Mixology::Drink.
type Drink struct {
	UID         cedar.EntityUID
	Tags        map[string]string
	Category    string
	Description string
	Glass       string
	Name        string
}

// CedarEntity converts m to the entity shape declared in schema.cedarschema.
func (m Drink) CedarEntity() cedar.Entity {
	tags := make(cedar.RecordMap, len(m.Tags))
	for key, value := range m.Tags {
		tags[cedar.String(key)] = cedar.String(value)
	}

	return cedar.Entity{
		UID:     cedar.NewEntityUID(DrinkType, m.UID.ID),
		Parents: cedar.NewEntityUIDSet(),
		Attributes: cedar.NewRecord(cedar.RecordMap{
			DrinkCategoryAttr:    cedar.String(m.Category),
			DrinkDescriptionAttr: cedar.String(m.Description),
			DrinkGlassAttr:       cedar.String(m.Glass),
			DrinkNameAttr:        cedar.String(m.Name),
		}),
		Tags: cedar.NewRecord(tags),
	}
}
