// Code generated by authz/gen from schema.cedarschema. DO NOT EDIT.

package authz

import (
	_ "embed"

	cedar "github.com/cedar-policy/cedar-go"
)

//go:embed schema.cedarschema
var Schema string

const (
	DrinkType            cedar.EntityType = "Mixology::Drink"
	ActionType           cedar.EntityType = "Mixology::Drink::Action"
	DrinkCategoryAttr                     = "Category"
	DrinkDescriptionAttr                  = "Description"
	DrinkGlassAttr                        = "Glass"
	DrinkNameAttr                         = "Name"
)

var (
	ActionCreate = cedar.NewEntityUID(ActionType, "create")
	ActionDelete = cedar.NewEntityUID(ActionType, "delete")
	ActionGet    = cedar.NewEntityUID(ActionType, "get")
	ActionList   = cedar.NewEntityUID(ActionType, "list")
	ActionUpdate = cedar.NewEntityUID(ActionType, "update")
)

// Drink is the Cedar-facing authorization model for Mixology::Drink.
type Drink struct {
	UID         cedar.EntityUID
	Tags        map[string]string
	Category    string
	Description string
	Glass       string
	Name        string
}

// CedarEntity converts m to the entity shape declared in schema.cedarschema.
func (m Drink) CedarEntity() cedar.Entity {
	tags := make(cedar.RecordMap, len(m.Tags))
	for key, value := range m.Tags {
		tags[cedar.String(key)] = cedar.String(value)
	}

	return cedar.Entity{
		UID:     cedar.NewEntityUID(DrinkType, m.UID.ID),
		Parents: cedar.NewEntityUIDSet(),
		Attributes: cedar.NewRecord(cedar.RecordMap{
			DrinkCategoryAttr:    cedar.String(m.Category),
			DrinkDescriptionAttr: cedar.String(m.Description),
			DrinkGlassAttr:       cedar.String(m.Glass),
			DrinkNameAttr:        cedar.String(m.Name),
		}),
		Tags: cedar.NewRecord(tags),
	}
}
