// Code generated by authz/gen from schema.cedarschema. DO NOT EDIT.

package authz_test

import (
	"testing"

	moduleauthz "github.com/TheFellow/go-modular-monolith/app/domains/drinks/authz"
	"github.com/TheFellow/go-modular-monolith/pkg/testutil"
	cedar "github.com/cedar-policy/cedar-go"
)

func TestDrinkCedarEntity(t *testing.T) {
	t.Parallel()

	model := moduleauthz.Drink{
		UID:         cedar.NewEntityUID("Wrong::Type", "test-id"),
		Category:    "test-category",
		Description: "test-description",
		Glass:       "test-glass",
		Name:        "test-name",
	}

	got := model.CedarEntity()
	want := cedar.Entity{
		UID:     cedar.NewEntityUID(moduleauthz.DrinkType, "test-id"),
		Parents: cedar.NewEntityUIDSet(),
		Attributes: cedar.NewRecord(cedar.RecordMap{
			moduleauthz.DrinkCategoryAttr:    cedar.String("test-category"),
			moduleauthz.DrinkDescriptionAttr: cedar.String("test-description"),
			moduleauthz.DrinkGlassAttr:       cedar.String("test-glass"),
			moduleauthz.DrinkNameAttr:        cedar.String("test-name"),
		}),
		Tags: cedar.NewRecord(nil),
	}

	testutil.ErrorIf(t, !want.Equal(got), "CedarEntity() = %#v, want %#v", got, want)
}
