// Code generated by errors/internal/gen; DO NOT EDIT.
package testutil

import (
	"testing"

	"github.com/TheFellow/go-modular-monolith/pkg/errors"
)

// ErrorIsInvalid fails the test if err is not a Invalid error.
func ErrorIsInvalid(t testing.TB, err error) {
	t.Helper()
	if err == nil || !errors.IsInvalid(err) {
		t.Fatalf("expected Invalid error, got %v", err)
	}
}

// ErrorIsNotFound fails the test if err is not a NotFound error.
func ErrorIsNotFound(t testing.TB, err error) {
	t.Helper()
	if err == nil || !errors.IsNotFound(err) {
		t.Fatalf("expected NotFound error, got %v", err)
	}
}

// ErrorIsPermission fails the test if err is not a Permission error.
func ErrorIsPermission(t testing.TB, err error) {
	t.Helper()
	if err == nil || !errors.IsPermission(err) {
		t.Fatalf("expected Permission error, got %v", err)
	}
}

// ErrorIsConflict fails the test if err is not a Conflict error.
func ErrorIsConflict(t testing.TB, err error) {
	t.Helper()
	if err == nil || !errors.IsConflict(err) {
		t.Fatalf("expected Conflict error, got %v", err)
	}
}

// ErrorIsInternal fails the test if err is not a Internal error.
func ErrorIsInternal(t testing.TB, err error) {
	t.Helper()
	if err == nil || !errors.IsInternal(err) {
		t.Fatalf("expected Internal error, got %v", err)
	}
}
