// Code generated by errors/gen; DO NOT EDIT.
package errors

import (
	stderrors "errors"
	"google.golang.org/grpc/codes"
)

type InvalidError struct {
	msg   string
	cause error
}

func (e *InvalidError) Error() string {
	if e == nil {
		return ErrInvalid.Message
	}
	if e.msg != "" {
		return e.msg
	}
	return ErrInvalid.Message
}

func (e *InvalidError) Unwrap() error        { return e.cause }
func (e *InvalidError) Kind() ErrorKind      { return ErrInvalid }
func (e *InvalidError) HTTPCode() httpCode   { return ErrInvalid.HTTPCode }
func (e *InvalidError) GRPCCode() codes.Code { return ErrInvalid.GRPCCode }
func (e *InvalidError) CLICode() int         { return ErrInvalid.CLICode }
func (e *InvalidError) ExitCode() int        { return ErrInvalid.CLICode }

func Invalidf(format string, args ...any) error {
	msg, cause := formatf(format, args...)
	return &InvalidError{msg: msg, cause: cause}
}

func IsInvalid(err error) bool {
	var target *InvalidError
	return stderrors.As(err, &target)
}

type NotFoundError struct {
	msg   string
	cause error
}

func (e *NotFoundError) Error() string {
	if e == nil {
		return ErrNotFound.Message
	}
	if e.msg != "" {
		return e.msg
	}
	return ErrNotFound.Message
}

func (e *NotFoundError) Unwrap() error        { return e.cause }
func (e *NotFoundError) Kind() ErrorKind      { return ErrNotFound }
func (e *NotFoundError) HTTPCode() httpCode   { return ErrNotFound.HTTPCode }
func (e *NotFoundError) GRPCCode() codes.Code { return ErrNotFound.GRPCCode }
func (e *NotFoundError) CLICode() int         { return ErrNotFound.CLICode }
func (e *NotFoundError) ExitCode() int        { return ErrNotFound.CLICode }

func NotFoundf(format string, args ...any) error {
	msg, cause := formatf(format, args...)
	return &NotFoundError{msg: msg, cause: cause}
}

func IsNotFound(err error) bool {
	var target *NotFoundError
	return stderrors.As(err, &target)
}

type PermissionError struct {
	msg   string
	cause error
}

func (e *PermissionError) Error() string {
	if e == nil {
		return ErrPermission.Message
	}
	if e.msg != "" {
		return e.msg
	}
	return ErrPermission.Message
}

func (e *PermissionError) Unwrap() error        { return e.cause }
func (e *PermissionError) Kind() ErrorKind      { return ErrPermission }
func (e *PermissionError) HTTPCode() httpCode   { return ErrPermission.HTTPCode }
func (e *PermissionError) GRPCCode() codes.Code { return ErrPermission.GRPCCode }
func (e *PermissionError) CLICode() int         { return ErrPermission.CLICode }
func (e *PermissionError) ExitCode() int        { return ErrPermission.CLICode }

func Permissionf(format string, args ...any) error {
	msg, cause := formatf(format, args...)
	return &PermissionError{msg: msg, cause: cause}
}

func IsPermission(err error) bool {
	var target *PermissionError
	return stderrors.As(err, &target)
}

type ConflictError struct {
	msg   string
	cause error
}

func (e *ConflictError) Error() string {
	if e == nil {
		return ErrConflict.Message
	}
	if e.msg != "" {
		return e.msg
	}
	return ErrConflict.Message
}

func (e *ConflictError) Unwrap() error        { return e.cause }
func (e *ConflictError) Kind() ErrorKind      { return ErrConflict }
func (e *ConflictError) HTTPCode() httpCode   { return ErrConflict.HTTPCode }
func (e *ConflictError) GRPCCode() codes.Code { return ErrConflict.GRPCCode }
func (e *ConflictError) CLICode() int         { return ErrConflict.CLICode }
func (e *ConflictError) ExitCode() int        { return ErrConflict.CLICode }

func Conflictf(format string, args ...any) error {
	msg, cause := formatf(format, args...)
	return &ConflictError{msg: msg, cause: cause}
}

func IsConflict(err error) bool {
	var target *ConflictError
	return stderrors.As(err, &target)
}

type InternalError struct {
	msg   string
	cause error
}

func (e *InternalError) Error() string {
	if e == nil {
		return ErrInternal.Message
	}
	if e.msg != "" {
		return e.msg
	}
	return ErrInternal.Message
}

func (e *InternalError) Unwrap() error        { return e.cause }
func (e *InternalError) Kind() ErrorKind      { return ErrInternal }
func (e *InternalError) HTTPCode() httpCode   { return ErrInternal.HTTPCode }
func (e *InternalError) GRPCCode() codes.Code { return ErrInternal.GRPCCode }
func (e *InternalError) CLICode() int         { return ErrInternal.CLICode }
func (e *InternalError) ExitCode() int        { return ErrInternal.CLICode }

func Internalf(format string, args ...any) error {
	msg, cause := formatf(format, args...)
	return &InternalError{msg: msg, cause: cause}
}

func IsInternal(err error) bool {
	var target *InternalError
	return stderrors.As(err, &target)
}
