// Code generated by authz/gen from schema.cedarschema. DO NOT EDIT.

package authz

import (
	"testing"

	cedar "github.com/cedar-policy/cedar-go"
)

func TestOrderCedarEntity(t *testing.T) {
	t.Parallel()

	model := Order{
		UID:    cedar.NewEntityUID("Wrong::Type", "test-id"),
		MenuID: cedar.NewEntityUID("Test::Reference", "test-menuid"),
		Status: "test-status",
	}

	got := model.CedarEntity()
	want := cedar.Entity{
		UID:     cedar.NewEntityUID(OrderType, "test-id"),
		Parents: cedar.NewEntityUIDSet(),
		Attributes: cedar.NewRecord(cedar.RecordMap{
			OrderMenuIDAttr: cedar.NewEntityUID("Test::Reference", "test-menuid"),
			OrderStatusAttr: cedar.String("test-status"),
		}),
		Tags: cedar.NewRecord(nil),
	}

	if !want.Equal(got) {
		t.Errorf("CedarEntity() = %#v, want %#v", got, want)
	}
}
