// Code generated by authz/gen from schema.cedarschema. DO NOT EDIT.

package authz_test

import (
	"testing"

	moduleauthz "github.com/TheFellow/go-modular-monolith/app/domains/orders/authz"
	"github.com/TheFellow/go-modular-monolith/pkg/testutil"
	cedar "github.com/cedar-policy/cedar-go"
)

func TestOrderCedarEntity(t *testing.T) {
	t.Parallel()

	model := moduleauthz.Order{
		UID:    cedar.NewEntityUID("Wrong::Type", "test-id"),
		MenuID: cedar.NewEntityUID("Test::Reference", "test-menuid"),
		Status: "test-status",
	}

	got := model.CedarEntity()
	want := cedar.Entity{
		UID:     cedar.NewEntityUID(moduleauthz.OrderType, "test-id"),
		Parents: cedar.NewEntityUIDSet(),
		Attributes: cedar.NewRecord(cedar.RecordMap{
			moduleauthz.OrderMenuIDAttr: cedar.NewEntityUID("Test::Reference", "test-menuid"),
			moduleauthz.OrderStatusAttr: cedar.String("test-status"),
		}),
		Tags: cedar.NewRecord(nil),
	}

	testutil.ErrorIf(t, !want.Equal(got), "CedarEntity() = %#v, want %#v", got, want)
}
