// Code generated by authz/gen from schema.cedarschema. DO NOT EDIT.

package authz

import (
	_ "embed"

	cedar "github.com/cedar-policy/cedar-go"
)

//go:embed schema.cedarschema
var Schema string

const (
	OrderType       cedar.EntityType = "Mixology::Order"
	ActionType      cedar.EntityType = "Mixology::Order::Action"
	OrderMenuIDAttr                  = "MenuID"
	OrderStatusAttr                  = "Status"
)

var (
	ActionCancel   = cedar.NewEntityUID(ActionType, "cancel")
	ActionComplete = cedar.NewEntityUID(ActionType, "complete")
	ActionGet      = cedar.NewEntityUID(ActionType, "get")
	ActionList     = cedar.NewEntityUID(ActionType, "list")
	ActionPlace    = cedar.NewEntityUID(ActionType, "place")
)

// Order is the Cedar-facing authorization model for Mixology::Order.
type Order struct {
	UID    cedar.EntityUID
	MenuID cedar.EntityUID
	Status string
}

// CedarEntity converts m to the entity shape declared in schema.cedarschema.
func (m Order) CedarEntity() cedar.Entity {
	return cedar.Entity{
		UID:     cedar.NewEntityUID(OrderType, m.UID.ID),
		Parents: cedar.NewEntityUIDSet(),
		Attributes: cedar.NewRecord(cedar.RecordMap{
			OrderMenuIDAttr: cedar.EntityUID(m.MenuID),
			OrderStatusAttr: cedar.String(m.Status),
		}),
		Tags: cedar.NewRecord(nil),
	}
}
