// Code generated by authz/gen from schema.cedarschema. DO NOT EDIT.

package authz

import (
	_ "embed"
	"sync"

	cedar "github.com/cedar-policy/cedar-go"
	"github.com/cedar-policy/cedar-go/x/exp/schema"
	"github.com/cedar-policy/cedar-go/x/exp/schema/resolved"
	"github.com/cedar-policy/cedar-go/x/exp/schema/validate"
)

//go:embed schema.cedarschema
var Schema string

const (
	OrderType       cedar.EntityType = "Mixology::Order"
	ResourceType    cedar.EntityType = OrderType
	ActionType      cedar.EntityType = "Mixology::Order::Action"
	OrderMenuIDAttr                  = "MenuID"
	OrderStatusAttr                  = "Status"
)

var (
	schemaOnce     sync.Once
	resolvedSchema *resolved.Schema
	schemaErr      error
)

// ValidateEntity validates entity against the module's Cedar schema.
func ValidateEntity(entity cedar.Entity) error {
	schemaOnce.Do(func() {
		var parsed schema.Schema
		parsed.SetFilename("schema.cedarschema")
		if schemaErr = parsed.UnmarshalCedar([]byte(Schema)); schemaErr != nil {
			return
		}
		resolvedSchema, schemaErr = parsed.Resolve()
	})
	if schemaErr != nil {
		return schemaErr
	}
	return validate.New(resolvedSchema).Entity(entity)
}

var (
	ActionCancel   = cedar.NewEntityUID(ActionType, "cancel")
	ActionComplete = cedar.NewEntityUID(ActionType, "complete")
	ActionGet      = cedar.NewEntityUID(ActionType, "get")
	ActionList     = cedar.NewEntityUID(ActionType, "list")
	ActionPlace    = cedar.NewEntityUID(ActionType, "place")
	ActionTag      = cedar.NewEntityUID(ActionType, "tag")
	ActionUntag    = cedar.NewEntityUID(ActionType, "untag")
)

// Order is the Cedar-facing authorization model for Mixology::Order.
type Order struct {
	UID    cedar.EntityUID
	Tags   map[string]string
	MenuID cedar.EntityUID
	Status string
}

// CedarEntity converts m to the entity shape declared in schema.cedarschema.
func (m Order) CedarEntity() cedar.Entity {
	tags := make(cedar.RecordMap, len(m.Tags))
	for key, value := range m.Tags {
		tags[cedar.String(key)] = cedar.String(value)
	}

	return cedar.Entity{
		UID:     cedar.NewEntityUID(OrderType, m.UID.ID),
		Parents: cedar.NewEntityUIDSet(),
		Attributes: cedar.NewRecord(cedar.RecordMap{
			OrderMenuIDAttr: cedar.NewEntityUID("Mixology::Menu", m.MenuID.ID),
			OrderStatusAttr: cedar.String(m.Status),
		}),
		Tags: cedar.NewRecord(tags),
	}
}
