// Code generated by policygen; DO NOT EDIT.
package authz

func policyDocuments() map[string]string {
	return map[string]string{
		"app/drinks/authz/policies.cedar": "// app/drinks/authz/policies.cedar\n\n// Read operations are open for now.\npermit(\n    principal,\n    action == Mixology::Drinks::Action::\"list\",\n    resource\n);\n\npermit(\n    principal,\n    action == Mixology::Drinks::Action::\"get\",\n    resource\n);\n\n// Write operations require an owner principal.\npermit(\n    principal == Mixology::Actor::\"owner\",\n    action == Mixology::Drinks::Action::\"create\",\n    resource\n);\n\n",
		"pkg/authz/base.cedar":            "// pkg/authz/base.cedar\n\n// Allow anonymous users to login (placeholder; real authn later).\npermit(\n    principal == Mixology::Actor::\"anonymous\",\n    action == Mixology::Action::\"login\",\n    resource == Mixology::Auth::Session::\"current\"\n);\n\n",
	}
}
