// Code generated by go generate; DO NOT EDIT.

package dispatcher

import (
	ingredients_events "github.com/TheFellow/go-modular-monolith/app/ingredients/events"
	ingredients_handlers "github.com/TheFellow/go-modular-monolith/app/ingredients/handlers"
	middleware "github.com/TheFellow/go-modular-monolith/pkg/middleware"
)

func (d *Dispatcher) Dispatch(ctx *middleware.Context, event any) error {
	switch e := event.(type) {
	case ingredients_events.IngredientCreated:
		if err := ingredients_handlers.NewIngredientCreatedAudit().Handle(ctx, e); err != nil {
			if herr := d.handlerError(ctx, e, err); herr != nil {
				return herr
			}
		}
		if err := ingredients_handlers.NewIngredientCreatedCounter().Handle(ctx, e); err != nil {
			if herr := d.handlerError(ctx, e, err); herr != nil {
				return herr
			}
		}
	default:
		return d.unhandledEvent(ctx, event)
	}
	return nil
}
