// Code generated by go generate; DO NOT EDIT.

package dispatcher

import (
{{- range .Imports }}
	{{ .Alias }} {{ printf "%q" .Path }}
{{- end }}
)

func (d *Dispatcher) Dispatch(ctx context.Context, event any) error {
	switch e := event.(type) {
{{- range .Groups }}
	case {{ index $.ImportAlias .Event.PkgPath }}.{{ .Event.Name }}:
{{- range .Handlers }}
		if err := {{ index $.ImportAlias .PkgPath }}.New{{ .Name }}().Handle(ctx, e); err != nil {
			if herr := d.handlerError(ctx, e, err); herr != nil {
				return herr
			}
		}
{{- end }}
{{- end }}
	default:
		return d.unhandledEvent(ctx, event)
	}
	return nil
}
