// Code generated by go generate; DO NOT EDIT.

package dispatcher

import (
	audit_handlers "github.com/TheFellow/go-modular-monolith/app/domains/audit/handlers"
	drinks_events "github.com/TheFellow/go-modular-monolith/app/domains/drinks/events"
	drinks_handlers "github.com/TheFellow/go-modular-monolith/app/domains/drinks/handlers"
	ingredients_events "github.com/TheFellow/go-modular-monolith/app/domains/ingredients/events"
	inventory_events "github.com/TheFellow/go-modular-monolith/app/domains/inventory/events"
	inventory_handlers "github.com/TheFellow/go-modular-monolith/app/domains/inventory/handlers"
	menu_events "github.com/TheFellow/go-modular-monolith/app/domains/menu/events"
	menu_handlers "github.com/TheFellow/go-modular-monolith/app/domains/menu/handlers"
	orders_events "github.com/TheFellow/go-modular-monolith/app/domains/orders/events"
	middleware "github.com/TheFellow/go-modular-monolith/pkg/middleware"
	pkg_events "github.com/TheFellow/go-modular-monolith/pkg/middleware/events"
)

func (d *Dispatcher) Dispatch(ctx *middleware.Context, event any) error {
	switch e := event.(type) {
	case drinks_events.DrinkDeleted:
		menuHandler := menu_handlers.NewDrinkDeleted()
		if err := menuHandler.Handle(ctx, e); err != nil {
			if herr := d.handlerError(ctx, e, err); herr != nil {
				return herr
			}
		}
	case drinks_events.DrinkUpdated:
		menuHandler := menu_handlers.NewDrinkUpdated()
		if err := menuHandler.Handle(ctx, e); err != nil {
			if herr := d.handlerError(ctx, e, err); herr != nil {
				return herr
			}
		}
	case ingredients_events.IngredientDeleted:
		drinksHandler := drinks_handlers.NewIngredientDeleted()
		inventoryHandler := inventory_handlers.NewIngredientDeleted()
		menuHandler := menu_handlers.NewIngredientDeleted()
		if err := drinksHandler.Handling(ctx, e); err != nil {
			if herr := d.handlerError(ctx, e, err); herr != nil {
				return herr
			}
		}
		if err := menuHandler.Handling(ctx, e); err != nil {
			if herr := d.handlerError(ctx, e, err); herr != nil {
				return herr
			}
		}
		if err := drinksHandler.Handle(ctx, e); err != nil {
			if herr := d.handlerError(ctx, e, err); herr != nil {
				return herr
			}
		}
		if err := inventoryHandler.Handle(ctx, e); err != nil {
			if herr := d.handlerError(ctx, e, err); herr != nil {
				return herr
			}
		}
		if err := menuHandler.Handle(ctx, e); err != nil {
			if herr := d.handlerError(ctx, e, err); herr != nil {
				return herr
			}
		}
	case ingredients_events.IngredientUpdated:
		drinksHandler := drinks_handlers.NewIngredientUpdated()
		menuHandler := menu_handlers.NewIngredientUpdated()
		if err := drinksHandler.Handle(ctx, e); err != nil {
			if herr := d.handlerError(ctx, e, err); herr != nil {
				return herr
			}
		}
		if err := menuHandler.Handle(ctx, e); err != nil {
			if herr := d.handlerError(ctx, e, err); herr != nil {
				return herr
			}
		}
	case inventory_events.StockAdjusted:
		menuHandler := menu_handlers.NewStockAdjusted()
		if err := menuHandler.Handle(ctx, e); err != nil {
			if herr := d.handlerError(ctx, e, err); herr != nil {
				return herr
			}
		}
	case menu_events.MenuPublished:
		menuHandler := menu_handlers.NewMenuPublished()
		if err := menuHandler.Handle(ctx, e); err != nil {
			if herr := d.handlerError(ctx, e, err); herr != nil {
				return herr
			}
		}
	case orders_events.OrderCompleted:
		inventoryHandler := inventory_handlers.NewOrderCompleted()
		menuHandler := menu_handlers.NewOrderCompleted()
		if err := inventoryHandler.Handle(ctx, e); err != nil {
			if herr := d.handlerError(ctx, e, err); herr != nil {
				return herr
			}
		}
		if err := menuHandler.Handle(ctx, e); err != nil {
			if herr := d.handlerError(ctx, e, err); herr != nil {
				return herr
			}
		}
	case pkg_events.ActivityCompleted:
		auditHandler := audit_handlers.NewActivityCompleted()
		if err := auditHandler.Handle(ctx, e); err != nil {
			if herr := d.handlerError(ctx, e, err); herr != nil {
				return herr
			}
		}
	default:
		return d.unhandledEvent(ctx, event)
	}
	return nil
}
