// Code generated by go generate; DO NOT EDIT.

package entity

import (
	"strings"

	"github.com/TheFellow/go-modular-monolith/pkg/errors"
	cedar "github.com/cedar-policy/cedar-go"
)

// Drink ID Types and Constants

const (
	TypeDrink   = cedar.EntityType("Mixology::Drink")
	PrefixDrink = "drk"
)

// DrinkID is a strongly-typed ID for Drink entities.
type DrinkID cedar.EntityUID

// NewDrinkID generates a new DrinkID.
func NewDrinkID() DrinkID {
	return DrinkID(NewID(TypeDrink, PrefixDrink))
}

// ParseDrinkID creates a DrinkID from a string.
func ParseDrinkID(id string) (DrinkID, error) {
	if id == "" {
		return DrinkID(cedar.NewEntityUID(TypeDrink, cedar.String(""))), nil
	}
	if !strings.HasPrefix(id, PrefixDrink+"-") {
		return DrinkID{}, errors.Invalidf("invalid drink id prefix: %s", id)
	}
	return DrinkID(cedar.NewEntityUID(TypeDrink, cedar.String(id))), nil
}

// EntityUID converts to cedar.EntityUID for Cedar API interop.
func (id DrinkID) EntityUID() cedar.EntityUID {
	return cedar.EntityUID(id)
}

// String returns the ID portion as a string.
func (id DrinkID) String() string {
	return string(cedar.EntityUID(id).ID)
}

// IsZero returns true if the ID is unset.
func (id DrinkID) IsZero() bool {
	return cedar.EntityUID(id).ID == ""
}

// Ingredient ID Types and Constants

const (
	TypeIngredient   = cedar.EntityType("Mixology::Ingredient")
	PrefixIngredient = "ing"
)

// IngredientID is a strongly-typed ID for Ingredient entities.
type IngredientID cedar.EntityUID

// NewIngredientID generates a new IngredientID.
func NewIngredientID() IngredientID {
	return IngredientID(NewID(TypeIngredient, PrefixIngredient))
}

// ParseIngredientID creates a IngredientID from a string.
func ParseIngredientID(id string) (IngredientID, error) {
	if id == "" {
		return IngredientID(cedar.NewEntityUID(TypeIngredient, cedar.String(""))), nil
	}
	if !strings.HasPrefix(id, PrefixIngredient+"-") {
		return IngredientID{}, errors.Invalidf("invalid ingredient id prefix: %s", id)
	}
	return IngredientID(cedar.NewEntityUID(TypeIngredient, cedar.String(id))), nil
}

// EntityUID converts to cedar.EntityUID for Cedar API interop.
func (id IngredientID) EntityUID() cedar.EntityUID {
	return cedar.EntityUID(id)
}

// String returns the ID portion as a string.
func (id IngredientID) String() string {
	return string(cedar.EntityUID(id).ID)
}

// IsZero returns true if the ID is unset.
func (id IngredientID) IsZero() bool {
	return cedar.EntityUID(id).ID == ""
}

// Menu ID Types and Constants

const (
	TypeMenu   = cedar.EntityType("Mixology::Menu")
	PrefixMenu = "mnu"
)

// MenuID is a strongly-typed ID for Menu entities.
type MenuID cedar.EntityUID

// NewMenuID generates a new MenuID.
func NewMenuID() MenuID {
	return MenuID(NewID(TypeMenu, PrefixMenu))
}

// ParseMenuID creates a MenuID from a string.
func ParseMenuID(id string) (MenuID, error) {
	if id == "" {
		return MenuID(cedar.NewEntityUID(TypeMenu, cedar.String(""))), nil
	}
	if !strings.HasPrefix(id, PrefixMenu+"-") {
		return MenuID{}, errors.Invalidf("invalid menu id prefix: %s", id)
	}
	return MenuID(cedar.NewEntityUID(TypeMenu, cedar.String(id))), nil
}

// EntityUID converts to cedar.EntityUID for Cedar API interop.
func (id MenuID) EntityUID() cedar.EntityUID {
	return cedar.EntityUID(id)
}

// String returns the ID portion as a string.
func (id MenuID) String() string {
	return string(cedar.EntityUID(id).ID)
}

// IsZero returns true if the ID is unset.
func (id MenuID) IsZero() bool {
	return cedar.EntityUID(id).ID == ""
}

// Order ID Types and Constants

const (
	TypeOrder   = cedar.EntityType("Mixology::Order")
	PrefixOrder = "ord"
)

// OrderID is a strongly-typed ID for Order entities.
type OrderID cedar.EntityUID

// NewOrderID generates a new OrderID.
func NewOrderID() OrderID {
	return OrderID(NewID(TypeOrder, PrefixOrder))
}

// ParseOrderID creates a OrderID from a string.
func ParseOrderID(id string) (OrderID, error) {
	if id == "" {
		return OrderID(cedar.NewEntityUID(TypeOrder, cedar.String(""))), nil
	}
	if !strings.HasPrefix(id, PrefixOrder+"-") {
		return OrderID{}, errors.Invalidf("invalid order id prefix: %s", id)
	}
	return OrderID(cedar.NewEntityUID(TypeOrder, cedar.String(id))), nil
}

// EntityUID converts to cedar.EntityUID for Cedar API interop.
func (id OrderID) EntityUID() cedar.EntityUID {
	return cedar.EntityUID(id)
}

// String returns the ID portion as a string.
func (id OrderID) String() string {
	return string(cedar.EntityUID(id).ID)
}

// IsZero returns true if the ID is unset.
func (id OrderID) IsZero() bool {
	return cedar.EntityUID(id).ID == ""
}

// Inventory ID Types and Constants

const (
	TypeInventory   = cedar.EntityType("Mixology::Inventory")
	PrefixInventory = "inv"
)

// InventoryID is a strongly-typed ID for Inventory entities.
type InventoryID cedar.EntityUID

// NewInventoryID generates a new InventoryID.
func NewInventoryID(source IngredientID) InventoryID {
	if source.IsZero() {
		return InventoryID(cedar.NewEntityUID(TypeInventory, cedar.String("")))
	}
	return InventoryID(cedar.NewEntityUID(TypeInventory, cedar.String(PrefixInventory+"-"+source.String())))
}

// ParseInventoryID creates a InventoryID from a string.
func ParseInventoryID(id string) (InventoryID, error) {
	if id == "" {
		return InventoryID(cedar.NewEntityUID(TypeInventory, cedar.String(""))), nil
	}
	if !strings.HasPrefix(id, PrefixInventory+"-") {
		return InventoryID{}, errors.Invalidf("invalid inventory id prefix: %s", id)
	}
	return InventoryID(cedar.NewEntityUID(TypeInventory, cedar.String(id))), nil
}

// EntityUID converts to cedar.EntityUID for Cedar API interop.
func (id InventoryID) EntityUID() cedar.EntityUID {
	return cedar.EntityUID(id)
}

// String returns the ID portion as a string.
func (id InventoryID) String() string {
	return string(cedar.EntityUID(id).ID)
}

// IsZero returns true if the ID is unset.
func (id InventoryID) IsZero() bool {
	return cedar.EntityUID(id).ID == ""
}

// AuditEntry ID Types and Constants

const (
	TypeAuditEntry   = cedar.EntityType("Mixology::AuditEntry")
	PrefixAuditEntry = "aud"
)

// AuditEntryID is a strongly-typed ID for AuditEntry entities.
type AuditEntryID cedar.EntityUID

// NewAuditEntryID generates a new AuditEntryID.
func NewAuditEntryID() AuditEntryID {
	return AuditEntryID(NewID(TypeAuditEntry, PrefixAuditEntry))
}

// ParseAuditEntryID creates a AuditEntryID from a string.
func ParseAuditEntryID(id string) (AuditEntryID, error) {
	if id == "" {
		return AuditEntryID(cedar.NewEntityUID(TypeAuditEntry, cedar.String(""))), nil
	}
	if !strings.HasPrefix(id, PrefixAuditEntry+"-") {
		return AuditEntryID{}, errors.Invalidf("invalid auditentry id prefix: %s", id)
	}
	return AuditEntryID(cedar.NewEntityUID(TypeAuditEntry, cedar.String(id))), nil
}

// EntityUID converts to cedar.EntityUID for Cedar API interop.
func (id AuditEntryID) EntityUID() cedar.EntityUID {
	return cedar.EntityUID(id)
}

// String returns the ID portion as a string.
func (id AuditEntryID) String() string {
	return string(cedar.EntityUID(id).ID)
}

// IsZero returns true if the ID is unset.
func (id AuditEntryID) IsZero() bool {
	return cedar.EntityUID(id).ID == ""
}
