// Code generated by authz/gen from schema.cedarschema. DO NOT EDIT.

package authz_test

import (
	"testing"

	moduleauthz "github.com/TheFellow/go-modular-monolith/app/domains/audit/authz"
	"github.com/TheFellow/go-modular-monolith/pkg/testutil"
	cedar "github.com/cedar-policy/cedar-go"
)

func TestAuditEntryCedarEntity(t *testing.T) {
	t.Parallel()

	model := moduleauthz.AuditEntry{
		UID: cedar.NewEntityUID("Wrong::Type", "test-id"),
	}

	got := model.CedarEntity()
	want := cedar.Entity{
		UID:        cedar.NewEntityUID(moduleauthz.AuditEntryType, "test-id"),
		Parents:    cedar.NewEntityUIDSet(),
		Attributes: cedar.NewRecord(cedar.RecordMap{}),
		Tags:       cedar.NewRecord(nil),
	}

	testutil.ErrorIf(t, !want.Equal(got), "CedarEntity() = %#v, want %#v", got, want)
}
