// Code generated by authz/gen from schema.cedarschema. DO NOT EDIT.

package authz_test

import (
	"testing"

	moduleauthz "github.com/TheFellow/go-modular-monolith/app/domains/audit/authz"
	"github.com/TheFellow/go-modular-monolith/pkg/testutil"
	cedar "github.com/cedar-policy/cedar-go"
	"github.com/cedar-policy/cedar-go/x/exp/schema"
	"github.com/cedar-policy/cedar-go/x/exp/schema/validate"
)

func TestAuditEntryCedarEntity(t *testing.T) {
	t.Parallel()

	model := moduleauthz.AuditEntry{
		UID: cedar.NewEntityUID("Wrong::Type", "test-id"),
	}

	got := model.CedarEntity()
	want := cedar.Entity{
		UID:        cedar.NewEntityUID(moduleauthz.AuditEntryType, "test-id"),
		Parents:    cedar.NewEntityUIDSet(),
		Attributes: cedar.NewRecord(cedar.RecordMap{}),
		Tags:       cedar.NewRecord(nil),
	}

	testutil.Equals(t, got, want)
	var parsed schema.Schema
	testutil.Ok(t, parsed.UnmarshalCedar([]byte(moduleauthz.Schema)))
	resolved, err := parsed.Resolve()
	testutil.Ok(t, err)
	testutil.Ok(t, validate.New(resolved).Entity(got))
}
