// Code generated by authz/gen from schema.cedarschema. DO NOT EDIT.

package authz

import (
	"testing"

	cedar "github.com/cedar-policy/cedar-go"
)

func TestAuditEntryCedarEntity(t *testing.T) {
	t.Parallel()

	model := AuditEntry{
		UID: cedar.NewEntityUID("Wrong::Type", "test-id"),
	}

	got := model.CedarEntity()
	want := cedar.Entity{
		UID:        cedar.NewEntityUID(AuditEntryType, "test-id"),
		Parents:    cedar.NewEntityUIDSet(),
		Attributes: cedar.NewRecord(cedar.RecordMap{}),
		Tags:       cedar.NewRecord(nil),
	}

	if !want.Equal(got) {
		t.Errorf("CedarEntity() = %#v, want %#v", got, want)
	}
}
