// Code generated by authz/gen from schema.cedarschema. DO NOT EDIT.

package authz

import (
	_ "embed"

	cedar "github.com/cedar-policy/cedar-go"
)

//go:embed schema.cedarschema
var Schema string

const (
	AuditEntryType cedar.EntityType = "Mixology::AuditEntry"
	ActionType     cedar.EntityType = "Mixology::AuditEntry::Action"
)

var (
	ActionGet  = cedar.NewEntityUID(ActionType, "get")
	ActionList = cedar.NewEntityUID(ActionType, "list")
)

// AuditEntry is the Cedar-facing authorization model for Mixology::AuditEntry.
type AuditEntry struct {
	UID cedar.EntityUID
}

// CedarEntity converts m to the entity shape declared in schema.cedarschema.
func (m AuditEntry) CedarEntity() cedar.Entity {
	return cedar.Entity{
		UID:        cedar.NewEntityUID(AuditEntryType, m.UID.ID),
		Parents:    cedar.NewEntityUIDSet(),
		Attributes: cedar.NewRecord(cedar.RecordMap{}),
		Tags:       cedar.NewRecord(nil),
	}
}
