// Code generated by authz/gen from schema.cedarschema. DO NOT EDIT.

package authz_test

import (
	"testing"

	moduleauthz "github.com/TheFellow/go-modular-monolith/app/domains/menus/authz"
	"github.com/TheFellow/go-modular-monolith/pkg/testutil"
	cedar "github.com/cedar-policy/cedar-go"
	"github.com/cedar-policy/cedar-go/x/exp/schema"
	"github.com/cedar-policy/cedar-go/x/exp/schema/validate"
)

func TestMenuCedarEntity(t *testing.T) {
	t.Parallel()

	model := moduleauthz.Menu{
		UID:    cedar.NewEntityUID("Wrong::Type", "test-id"),
		Tags:   map[string]string{"audience": "members", "featured": ""},
		Name:   "test-name",
		Status: "test-status",
	}

	got := model.CedarEntity()
	want := cedar.Entity{
		UID:     cedar.NewEntityUID(moduleauthz.MenuType, "test-id"),
		Parents: cedar.NewEntityUIDSet(),
		Attributes: cedar.NewRecord(cedar.RecordMap{
			moduleauthz.MenuNameAttr:   cedar.String("test-name"),
			moduleauthz.MenuStatusAttr: cedar.String("test-status"),
		}),
		Tags: cedar.NewRecord(cedar.RecordMap{
			"audience": cedar.String("members"),
			"featured": cedar.String(""),
		}),
	}

	testutil.Equals(t, got, want)
	var parsed schema.Schema
	testutil.Ok(t, parsed.UnmarshalCedar([]byte(moduleauthz.Schema)))
	resolved, err := parsed.Resolve()
	testutil.Ok(t, err)
	testutil.Ok(t, validate.New(resolved).Entity(got))
}
