// Code generated by authz/gen from schema.cedarschema. DO NOT EDIT.

package authz

import (
	_ "embed"

	cedar "github.com/cedar-policy/cedar-go"
)

//go:embed schema.cedarschema
var Schema string

const (
	MenuType       cedar.EntityType = "Mixology::Menu"
	ActionType     cedar.EntityType = "Mixology::Menu::Action"
	MenuNameAttr                    = "Name"
	MenuStatusAttr                  = "Status"
)

var (
	ActionAddDrink    = cedar.NewEntityUID(ActionType, "add_drink")
	ActionCreate      = cedar.NewEntityUID(ActionType, "create")
	ActionDelete      = cedar.NewEntityUID(ActionType, "delete")
	ActionDraft       = cedar.NewEntityUID(ActionType, "draft")
	ActionGet         = cedar.NewEntityUID(ActionType, "get")
	ActionList        = cedar.NewEntityUID(ActionType, "list")
	ActionPublish     = cedar.NewEntityUID(ActionType, "publish")
	ActionRemoveDrink = cedar.NewEntityUID(ActionType, "remove_drink")
	ActionUpdate      = cedar.NewEntityUID(ActionType, "update")
)

// Menu is the Cedar-facing authorization model for Mixology::Menu.
type Menu struct {
	UID    cedar.EntityUID
	Tags   map[string]string
	Name   string
	Status string
}

// CedarEntity converts m to the entity shape declared in schema.cedarschema.
func (m Menu) CedarEntity() cedar.Entity {
	tags := make(cedar.RecordMap, len(m.Tags))
	for key, value := range m.Tags {
		tags[cedar.String(key)] = cedar.String(value)
	}

	return cedar.Entity{
		UID:     cedar.NewEntityUID(MenuType, m.UID.ID),
		Parents: cedar.NewEntityUIDSet(),
		Attributes: cedar.NewRecord(cedar.RecordMap{
			MenuNameAttr:   cedar.String(m.Name),
			MenuStatusAttr: cedar.String(m.Status),
		}),
		Tags: cedar.NewRecord(tags),
	}
}
