// Code generated by authz/gen from schema.cedarschema. DO NOT EDIT.

package authz

import (
	"testing"

	cedar "github.com/cedar-policy/cedar-go"
)

func TestMenuCedarEntity(t *testing.T) {
	t.Parallel()

	model := Menu{
		UID:    cedar.NewEntityUID("Wrong::Type", "test-id"),
		Name:   "test-name",
		Status: "test-status",
	}

	got := model.CedarEntity()
	want := cedar.Entity{
		UID:     cedar.NewEntityUID(MenuType, "test-id"),
		Parents: cedar.NewEntityUIDSet(),
		Attributes: cedar.NewRecord(cedar.RecordMap{
			MenuNameAttr:   cedar.String("test-name"),
			MenuStatusAttr: cedar.String("test-status"),
		}),
		Tags: cedar.NewRecord(nil),
	}

	if !want.Equal(got) {
		t.Errorf("CedarEntity() = %#v, want %#v", got, want)
	}
}
