// Code generated by authz/gen from schema.cedarschema. DO NOT EDIT.

package authz

import (
	_ "embed"
	"sync"

	cedar "github.com/cedar-policy/cedar-go"
	"github.com/cedar-policy/cedar-go/x/exp/schema"
	"github.com/cedar-policy/cedar-go/x/exp/schema/resolved"
	"github.com/cedar-policy/cedar-go/x/exp/schema/validate"
)

//go:embed schema.cedarschema
var Schema string

const (
	MenuType       cedar.EntityType = "Mixology::Menu"
	ResourceType   cedar.EntityType = MenuType
	ActionType     cedar.EntityType = "Mixology::Menu::Action"
	MenuNameAttr                    = "Name"
	MenuStatusAttr                  = "Status"
)

var (
	schemaOnce     sync.Once
	resolvedSchema *resolved.Schema
	schemaErr      error
)

// ValidateEntity validates entity against the module's Cedar schema.
func ValidateEntity(entity cedar.Entity) error {
	schemaOnce.Do(func() {
		var parsed schema.Schema
		parsed.SetFilename("schema.cedarschema")
		if schemaErr = parsed.UnmarshalCedar([]byte(Schema)); schemaErr != nil {
			return
		}
		resolvedSchema, schemaErr = parsed.Resolve()
	})
	if schemaErr != nil {
		return schemaErr
	}
	return validate.New(resolvedSchema).Entity(entity)
}

var (
	ActionAddDrink    = cedar.NewEntityUID(ActionType, "add_drink")
	ActionCreate      = cedar.NewEntityUID(ActionType, "create")
	ActionDelete      = cedar.NewEntityUID(ActionType, "delete")
	ActionDraft       = cedar.NewEntityUID(ActionType, "draft")
	ActionGet         = cedar.NewEntityUID(ActionType, "get")
	ActionList        = cedar.NewEntityUID(ActionType, "list")
	ActionPublish     = cedar.NewEntityUID(ActionType, "publish")
	ActionReadiness   = cedar.NewEntityUID(ActionType, "readiness")
	ActionRemoveDrink = cedar.NewEntityUID(ActionType, "remove_drink")
	ActionTag         = cedar.NewEntityUID(ActionType, "tag")
	ActionUntag       = cedar.NewEntityUID(ActionType, "untag")
	ActionUpdate      = cedar.NewEntityUID(ActionType, "update")
)

// Menu is the Cedar-facing authorization model for Mixology::Menu.
type Menu struct {
	UID    cedar.EntityUID
	Tags   map[string]string
	Name   string
	Status string
}

// CedarEntity converts m to the entity shape declared in schema.cedarschema.
func (m Menu) CedarEntity() cedar.Entity {
	tags := make(cedar.RecordMap, len(m.Tags))
	for key, value := range m.Tags {
		tags[cedar.String(key)] = cedar.String(value)
	}

	return cedar.Entity{
		UID:     cedar.NewEntityUID(MenuType, m.UID.ID),
		Parents: cedar.NewEntityUIDSet(),
		Attributes: cedar.NewRecord(cedar.RecordMap{
			MenuNameAttr:   cedar.String(m.Name),
			MenuStatusAttr: cedar.String(m.Status),
		}),
		Tags: cedar.NewRecord(tags),
	}
}
