// Code generated by authz/gen from schema.cedarschema. DO NOT EDIT.

package authz_test

import (
	"testing"

	moduleauthz "github.com/TheFellow/go-modular-monolith/app/domains/menus/authz"
	"github.com/TheFellow/go-modular-monolith/pkg/testutil"
	cedar "github.com/cedar-policy/cedar-go"
)

func TestMenuCedarEntity(t *testing.T) {
	t.Parallel()

	model := moduleauthz.Menu{
		UID:    cedar.NewEntityUID("Wrong::Type", "test-id"),
		Name:   "test-name",
		Status: "test-status",
	}

	got := model.CedarEntity()
	want := cedar.Entity{
		UID:     cedar.NewEntityUID(moduleauthz.MenuType, "test-id"),
		Parents: cedar.NewEntityUIDSet(),
		Attributes: cedar.NewRecord(cedar.RecordMap{
			moduleauthz.MenuNameAttr:   cedar.String("test-name"),
			moduleauthz.MenuStatusAttr: cedar.String("test-status"),
		}),
		Tags: cedar.NewRecord(nil),
	}

	testutil.Equals(t, got, want)
}
