// Code generated by authz/gen from schema.cedarschema. DO NOT EDIT.

package authz

import (
	_ "embed"
	"sync"

	cedar "github.com/cedar-policy/cedar-go"
	"github.com/cedar-policy/cedar-go/x/exp/schema"
	"github.com/cedar-policy/cedar-go/x/exp/schema/resolved"
	"github.com/cedar-policy/cedar-go/x/exp/schema/validate"
)

//go:embed schema.cedarschema
var Schema string

const (
	TagDiscoveryType      cedar.EntityType = "Mixology::TagDiscovery"
	ResourceType          cedar.EntityType = TagDiscoveryType
	ActionType            cedar.EntityType = "Mixology::TagDiscovery::Action"
	TagDiscoveryExactAttr                  = "Exact"
	TagDiscoveryKeyAttr                    = "Key"
	TagDiscoveryValueAttr                  = "Value"
)

var (
	schemaOnce     sync.Once
	resolvedSchema *resolved.Schema
	schemaErr      error
)

// ValidateEntity validates entity against the module's Cedar schema.
func ValidateEntity(entity cedar.Entity) error {
	schemaOnce.Do(func() {
		var parsed schema.Schema
		parsed.SetFilename("schema.cedarschema")
		if schemaErr = parsed.UnmarshalCedar([]byte(Schema)); schemaErr != nil {
			return
		}
		resolvedSchema, schemaErr = parsed.Resolve()
	})
	if schemaErr != nil {
		return schemaErr
	}
	return validate.New(resolvedSchema).Entity(entity)
}

var (
	ActionShow    = cedar.NewEntityUID(ActionType, "show")
	ActionSummary = cedar.NewEntityUID(ActionType, "summary")
)

// TagDiscovery is the Cedar-facing authorization model for Mixology::TagDiscovery.
type TagDiscovery struct {
	UID   cedar.EntityUID
	Exact bool
	Key   string
	Value string
}

// CedarEntity converts m to the entity shape declared in schema.cedarschema.
func (m TagDiscovery) CedarEntity() cedar.Entity {
	return cedar.Entity{
		UID:     cedar.NewEntityUID(TagDiscoveryType, m.UID.ID),
		Parents: cedar.NewEntityUIDSet(),
		Attributes: cedar.NewRecord(cedar.RecordMap{
			TagDiscoveryExactAttr: cedar.Boolean(m.Exact),
			TagDiscoveryKeyAttr:   cedar.String(m.Key),
			TagDiscoveryValueAttr: cedar.String(m.Value),
		}),
		Tags: cedar.NewRecord(nil),
	}
}
