// Code generated by authz/gen from schema.cedarschema. DO NOT EDIT.

package authz

import (
	_ "embed"

	cedar "github.com/cedar-policy/cedar-go"
)

//go:embed schema.cedarschema
var Schema string

const (
	IngredientType         cedar.EntityType = "Mixology::Ingredient"
	ActionType             cedar.EntityType = "Mixology::Ingredient::Action"
	IngredientCategoryAttr                  = "Category"
	IngredientNameAttr                      = "Name"
	IngredientUnitAttr                      = "Unit"
)

var (
	ActionCreate = cedar.NewEntityUID(ActionType, "create")
	ActionDelete = cedar.NewEntityUID(ActionType, "delete")
	ActionGet    = cedar.NewEntityUID(ActionType, "get")
	ActionList   = cedar.NewEntityUID(ActionType, "list")
	ActionUpdate = cedar.NewEntityUID(ActionType, "update")
)

// Ingredient is the Cedar-facing authorization model for Mixology::Ingredient.
type Ingredient struct {
	UID      cedar.EntityUID
	Tags     map[string]string
	Category string
	Name     string
	Unit     string
}

// CedarEntity converts m to the entity shape declared in schema.cedarschema.
func (m Ingredient) CedarEntity() cedar.Entity {
	tags := make(cedar.RecordMap, len(m.Tags))
	for key, value := range m.Tags {
		tags[cedar.String(key)] = cedar.String(value)
	}

	return cedar.Entity{
		UID:     cedar.NewEntityUID(IngredientType, m.UID.ID),
		Parents: cedar.NewEntityUIDSet(),
		Attributes: cedar.NewRecord(cedar.RecordMap{
			IngredientCategoryAttr: cedar.String(m.Category),
			IngredientNameAttr:     cedar.String(m.Name),
			IngredientUnitAttr:     cedar.String(m.Unit),
		}),
		Tags: cedar.NewRecord(tags),
	}
}
