// Code generated by authz/gen from schema.cedarschema. DO NOT EDIT.

package authz_test

import (
	"testing"

	moduleauthz "github.com/TheFellow/go-modular-monolith/app/domains/ingredients/authz"
	"github.com/TheFellow/go-modular-monolith/pkg/testutil"
	cedar "github.com/cedar-policy/cedar-go"
)

func TestIngredientCedarEntity(t *testing.T) {
	t.Parallel()

	model := moduleauthz.Ingredient{
		UID:      cedar.NewEntityUID("Wrong::Type", "test-id"),
		Category: "test-category",
		Name:     "test-name",
		Unit:     "test-unit",
	}

	got := model.CedarEntity()
	want := cedar.Entity{
		UID:     cedar.NewEntityUID(moduleauthz.IngredientType, "test-id"),
		Parents: cedar.NewEntityUIDSet(),
		Attributes: cedar.NewRecord(cedar.RecordMap{
			moduleauthz.IngredientCategoryAttr: cedar.String("test-category"),
			moduleauthz.IngredientNameAttr:     cedar.String("test-name"),
			moduleauthz.IngredientUnitAttr:     cedar.String("test-unit"),
		}),
		Tags: cedar.NewRecord(nil),
	}

	testutil.Equals(t, got, want)
}
