// Code generated by authz/gen from schema.cedarschema. DO NOT EDIT.

package authz

import (
	_ "embed"
	"sync"

	cedar "github.com/cedar-policy/cedar-go"
	"github.com/cedar-policy/cedar-go/x/exp/schema"
	"github.com/cedar-policy/cedar-go/x/exp/schema/resolved"
	"github.com/cedar-policy/cedar-go/x/exp/schema/validate"
)

//go:embed schema.cedarschema
var Schema string

const (
	IngredientType         cedar.EntityType = "Mixology::Ingredient"
	ResourceType           cedar.EntityType = IngredientType
	ActionType             cedar.EntityType = "Mixology::Ingredient::Action"
	IngredientCategoryAttr                  = "Category"
	IngredientNameAttr                      = "Name"
	IngredientUnitAttr                      = "Unit"
)

var (
	schemaOnce     sync.Once
	resolvedSchema *resolved.Schema
	schemaErr      error
)

// ValidateEntity validates entity against the module's Cedar schema.
func ValidateEntity(entity cedar.Entity) error {
	schemaOnce.Do(func() {
		var parsed schema.Schema
		parsed.SetFilename("schema.cedarschema")
		if schemaErr = parsed.UnmarshalCedar([]byte(Schema)); schemaErr != nil {
			return
		}
		resolvedSchema, schemaErr = parsed.Resolve()
	})
	if schemaErr != nil {
		return schemaErr
	}
	return validate.New(resolvedSchema).Entity(entity)
}

var (
	ActionCreate = cedar.NewEntityUID(ActionType, "create")
	ActionDelete = cedar.NewEntityUID(ActionType, "delete")
	ActionGet    = cedar.NewEntityUID(ActionType, "get")
	ActionList   = cedar.NewEntityUID(ActionType, "list")
	ActionTag    = cedar.NewEntityUID(ActionType, "tag")
	ActionUntag  = cedar.NewEntityUID(ActionType, "untag")
	ActionUpdate = cedar.NewEntityUID(ActionType, "update")
)

// Ingredient is the Cedar-facing authorization model for Mixology::Ingredient.
type Ingredient struct {
	UID      cedar.EntityUID
	Tags     map[string]string
	Category string
	Name     string
	Unit     string
}

// CedarEntity converts m to the entity shape declared in schema.cedarschema.
func (m Ingredient) CedarEntity() cedar.Entity {
	tags := make(cedar.RecordMap, len(m.Tags))
	for key, value := range m.Tags {
		tags[cedar.String(key)] = cedar.String(value)
	}

	return cedar.Entity{
		UID:     cedar.NewEntityUID(IngredientType, m.UID.ID),
		Parents: cedar.NewEntityUIDSet(),
		Attributes: cedar.NewRecord(cedar.RecordMap{
			IngredientCategoryAttr: cedar.String(m.Category),
			IngredientNameAttr:     cedar.String(m.Name),
			IngredientUnitAttr:     cedar.String(m.Unit),
		}),
		Tags: cedar.NewRecord(tags),
	}
}
