// Code generated by authz/gen from schema.cedarschema. DO NOT EDIT.

package authz

import (
	"testing"

	cedar "github.com/cedar-policy/cedar-go"
)

func TestIngredientCedarEntity(t *testing.T) {
	t.Parallel()

	model := Ingredient{
		UID:      cedar.NewEntityUID("Wrong::Type", "test-id"),
		Category: "test-category",
		Name:     "test-name",
		Unit:     "test-unit",
	}

	got := model.CedarEntity()
	want := cedar.Entity{
		UID:     cedar.NewEntityUID(IngredientType, "test-id"),
		Parents: cedar.NewEntityUIDSet(),
		Attributes: cedar.NewRecord(cedar.RecordMap{
			IngredientCategoryAttr: cedar.String("test-category"),
			IngredientNameAttr:     cedar.String("test-name"),
			IngredientUnitAttr:     cedar.String("test-unit"),
		}),
		Tags: cedar.NewRecord(nil),
	}

	if !want.Equal(got) {
		t.Errorf("CedarEntity() = %#v, want %#v", got, want)
	}
}
