package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"
)

type modulePolicy struct {
	moduleName  string
	importAlias string
	importPath  string
	document    string
}

func main() {
	var out string
	flag.StringVar(&out, "out", "policies_gen.go", "output file (relative to pkg/authz)")
	flag.Parse()

	wd, err := os.Getwd()
	must(err)
	repoRoot := filepath.Clean(filepath.Join(wd, "..", ".."))

	modulePath := readModulePath(filepath.Join(repoRoot, "go.mod"))
	modules := discoverModulePolicies(repoRoot, modulePath)

	buf := &bytes.Buffer{}
	fmt.Fprintln(buf, "// Code generated by policygen; DO NOT EDIT.")
	fmt.Fprintln(buf, "package authz")
	fmt.Fprintln(buf, "")

	if len(modules) > 0 {
		fmt.Fprintln(buf, "import (")
		for _, m := range modules {
			fmt.Fprintf(buf, "\t%s %q\n", m.importAlias, m.importPath)
		}
		fmt.Fprintln(buf, ")")
		fmt.Fprintln(buf, "")
	}

	fmt.Fprintln(buf, "func policyDocuments() []PolicyDocument {")
	fmt.Fprintln(buf, "\treturn []PolicyDocument{")
	fmt.Fprintln(buf, "\t\t{Name: \"pkg/authz/base.cedar\", Text: basePolicies},")
	for _, m := range modules {
		fmt.Fprintf(buf, "\t\t{Name: %q, Text: %s.Policies},\n", m.document, m.importAlias)
	}
	fmt.Fprintln(buf, "\t}")
	fmt.Fprintln(buf, "}")

	formatted, err := format.Source(buf.Bytes())
	must(err)

	outPath := filepath.Join(wd, out)
	must(os.WriteFile(outPath, formatted, 0o644))
}

func readModulePath(goModPath string) string {
	b, err := os.ReadFile(goModPath)
	must(err)

	for _, line := range strings.Split(string(b), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "//") {
			continue
		}
		if rest, ok := strings.CutPrefix(line, "module "); ok {
			rest = strings.TrimSpace(rest)
			if rest != "" {
				return rest
			}
		}
	}
	panic("go.mod: missing module declaration")
}

func discoverModulePolicies(repoRoot, modulePath string) []modulePolicy {
	appDir := filepath.Join(repoRoot, "app")

	entries, err := os.ReadDir(appDir)
	must(err)

	var modules []modulePolicy
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}

		moduleName := e.Name()
		policiesPath := filepath.Join(appDir, moduleName, "authz", "policies.cedar")
		if _, err := os.Stat(policiesPath); err != nil {
			continue
		}

		importAlias := sanitizeIdent(moduleName) + "authz"
		if importAlias == "authz" {
			importAlias = "moduleauthz"
		}

		modules = append(modules, modulePolicy{
			moduleName:  moduleName,
			importAlias: importAlias,
			importPath:  modulePath + "/app/" + moduleName + "/authz",
			document:    filepath.ToSlash(filepath.Join("app", moduleName, "authz", "policies.cedar")),
		})
	}

	sort.Slice(modules, func(i, j int) bool {
		return modules[i].moduleName < modules[j].moduleName
	})
	return modules
}

func sanitizeIdent(s string) string {
	var b strings.Builder
	for i, r := range s {
		switch {
		case r == '_' || unicode.IsLetter(r) || (i > 0 && unicode.IsDigit(r)):
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	out := strings.Trim(b.String(), "_")
	out = strings.ToLower(out)
	if out == "" {
		return ""
	}
	if out[0] >= '0' && out[0] <= '9' {
		return "_" + out
	}
	return out
}

func must(err error) {
	if err != nil {
		panic(err)
	}
}
